### ISSUE TITLE
Exclude links from target removal

### ISSUE THREAD

**Issue by galbaras** [joedolson/wp-accessibility#25]
As per [this forum thread](https://wordpress.org/support/topic/allow-specific-links-to-open-in-a-new-tab/), it would be good to provide a way to leave the `target` attribute on some links.

Possibly the easiest way to do this would be to change [line 328 of wp-accessibility.php](https://github.com/joedolson/wp-accessibility/blob/40c73d6664a963bc5581bc952fbc63750ebfd0b0/src/wp-accessibility.php#L328) from:

`	$targets          = ( 'on' === get_option( 'wpa_target' ) ) ? "$('a').removeAttr('target');" : '';`

To:

`	$targets          = ( 'on' === get_option( 'wpa_target' ) ) ? "$('a:not([data-target="keep"])').removeAttr('target');" : '';`

This way, if a site builder wants to allow a link to open in a new tab, all they need to do is add `data-target="keep"` to the anchor tag and the script will ignore it.

**Comment by leonstafford** [comment]
@galbaras, having read that forum, I'm still unsure your intentions for this. Is it in any way aiming to improve accessibility for users or to circumvent accessibility for some reason?

**Comment by galbaras** [comment]
In general, it's good to remove the `target` attribute from links, but there are some exceptions. One case I've bumped into was links in a Google Reviews widget, where I don't want users to lose their place on the site and navigate away. I prefer that the Google links open in a new tab, so that when the users finish reading them, they will return to my site easily.

Turning off `target` removal is just too much when all I want is to exclude specific links.

**Comment by leonstafford** [comment]
Yeah, I can understand where you're coming from.

Unfortunately, this is where site conversions would come at the cost of accessibility for those users who need it the most. As such, I wouldn't expect it to be accommodated in a plugin which aims to improve accessibility.

**Comment by galbaras** [comment]
Yet this plugin offers the removal of the attribute as an OPTION, which can be completely turned off. Surely those who benefit from the removal are better off when most links open in the same tab than if none of them do.

**Comment by leonstafford** [comment]
@galbaras great point! I'd go for forced on across the board myself. Your solution makes sense to me now!

**Comment by joedolson** [comment]
I still have some concerns about doing this. 

1) It is already possible for a site owner to implement their own method of opening links in new tabs. For example, using

`$('a([data-target="keep"])').attr( 'target', '_blank' );`

and running it after WP Accessibility has executed would restore the target. In either case, the site owner has to take some step to make anything happen; the change in my plug-in would not create any change of behavior by default.

2) Your argument in the support thread is exactly the kind of thing I want to make difficult: 'For example, I want the Google Reviews widget links to open in another tab.' The fact that you *want* links to open in a new tab doesn't entitle you to create a less accessible experience for users. There are only a few cases where a link really should open in a new tab by default: mostly because if the link opens in the same view, it'll cause a loss of data or a loss of position. E.g., in the middle of a form. 

3) The goal of this plug-in is to provide temporary solutions for users to enable while they go through their site and fix the problem. I'm certainly aware of the fact that many users don't do that: they implement the plug-in and allow it to address their problem forever. Allowing users to customize the behavior of the plug-in so that it matches their needs more accurately just means they're that much less likely to fix the problem on their site, and instead depend on the plugin. 

As always, I'm open to arguments - and you're absolutely right that this is an easy change to make, but it's also contrary to the intent of the plug-in.

**Comment by galbaras** [comment]
There's a difference between helping people do something you find worthwhile and forcing them to do it. The main advantage of the WordPress architecture is its programming hooks. The reason WooCommerce is so successful is that you can pretty much customise everything in it with hooks.

The WooCommerce (or WordPress) team doesn't judge your intended use of their hooks. They assume that their code doesn't account for every possibility and let site builders extend or adapt the code on their sites by providing hooks everywhere.

I would very much like to be considerate to all people, and I find inclusion and accessibility important. Not just online, BTW, and not just professionally. However, when a client pays me to build a site that makes them successful in business, I sometimes have to go with the majority when making UX decisions. It's unfair (personally, I don't hear as well as other people, so I know a bit about it), but it's part of reality.

> It is already possible for a site owner to implement their own method of opening links in new tabs

The inline script is written to the page with priority 100 during `wp_footer`. For anyone else reading this, I guess the overriding script can be written using priority 101 (or any other higher number).

Thank you for a very useful plugin and input.

**Comment by joedolson** [comment]
I certainly understand that clients sometimes insist on implementations that aren't accessible, and you may be stuck doing that. And WordPress offers the flexibility that you can absolutely do that, whether I implement this or not - which is my biggest argument against it.
